# Asset-Specific Trading Strategies Configuration
# Optimized configurations for 14 different synthetic indices

# Lot sizes for each asset
lot_sizes:
  "1HZ75V": 0.05
  "R_75": 0.01
  "R_100": 0.5
  "1HZ100V": 0.2
  "R_50": 4.0
  "1HZ50V": 0.01
  "R_25": 0.5
  "R_10": 0.5
  "1HZ10V": 0.5
  "1HZ25V": 0.01
  "stpRNG": 0.1
  "stpRNG2": 0.1
  "stpRNG3": 0.1
  "stpRNG4": 0.1
  "stpRNG5": 0.1

# Asset-specific strategy configurations
assets:
  # Volatility Indices - Fast momentum strategies
  R_75:
    strategy: "EMA_FAST"
    timeframe: "1H"
    indicators:
      - "EMA_12"
      - "EMA_26"
      - "RSI_14"
    multiplier: 0.01
    
  R_100:
    strategy: "EMA_FAST"
    timeframe: "1H"
    indicators:
      - "EMA_12"
      - "EMA_26"
      - "MACD"
    multiplier: 0.5
    
  R_50:
    strategy: "EMA_FAST"
    timeframe: "1H"
    indicators:
      - "EMA_9"
      - "EMA_21"
      - "RSI_14"
    multiplier: 4.0
    
  R_25:
    strategy: "EMA_FAST"
    timeframe: "1H"
    indicators:
      - "EMA_12"
      - "EMA_26"
      - "STOCH"
    multiplier: 0.5
    
  R_10:
    strategy: "EMA_FAST"
    timeframe: "1H"
    indicators:
      - "EMA_8"
      - "EMA_21"
      - "RSI_21"
    multiplier: 0.5

  # HZ Indices - Hybrid strategies with gap detection
  1HZ75V:
    strategy: "HYBRID_EMA_SMA"
    timeframe: "30M"
    indicators:
      - "EMA_12"
      - "SMA_20"
      - "GAP_DETECTION"
    multiplier: 0.05
    
  1HZ100V:
    strategy: "HYBRID_EMA_SMA"
    timeframe: "30M"
    indicators:
      - "EMA_12"
      - "SMA_20"
      - "GAP_DETECTION"
    multiplier: 0.2
    
  1HZ50V:
    strategy: "HYBRID_EMA_SMA"
    timeframe: "30M"
    indicators:
      - "EMA_12"
      - "SMA_20"
      - "GAP_DETECTION"
    multiplier: 0.01
    
  1HZ10V:
    strategy: "HYBRID_EMA_SMA"
    timeframe: "30M"
    indicators:
      - "EMA_12"
      - "SMA_20"
      - "GAP_DETECTION"
    multiplier: 0.5
    
  1HZ25V:
    strategy: "HYBRID_EMA_SMA"
    timeframe: "30M"
    indicators:
      - "EMA_12"
      - "SMA_20"
      - "GAP_DETECTION"
    multiplier: 0.01

  # Step Indices - Range-bound strategies
  stpRNG:
    strategy: "BOLLINGER_RSI"
    timeframe: "5M"
    indicators:
      - "BOLLINGER_BANDS"
      - "RSI_14"
      - "SUPPORT_RESISTANCE"
    multiplier: 0.1
    
  stpRNG2:
    strategy: "BOLLINGER_RSI"
    timeframe: "5M"
    indicators:
      - "BOLLINGER_BANDS"
      - "RSI_14"
      - "SUPPORT_RESISTANCE"
    multiplier: 0.1
    
  stpRNG3:
    strategy: "BOLLINGER_RSI"
    timeframe: "5M"
    indicators:
      - "BOLLINGER_BANDS"
      - "RSI_14"
      - "SUPPORT_RESISTANCE"
    multiplier: 0.1
    
  stpRNG4:
    strategy: "BOLLINGER_RSI"
    timeframe: "5M"
    indicators:
      - "BOLLINGER_BANDS"
      - "RSI_14"
      - "SUPPORT_RESISTANCE"
    multiplier: 0.1
    
  stpRNG5:
    strategy: "BOLLINGER_RSI"
    timeframe: "5M"
    indicators:
      - "BOLLINGER_BANDS"
      - "RSI_14"
      - "SUPPORT_RESISTANCE"
    multiplier: 0.1